### ISSUE TITLE
Is this still a thing?

### ISSUE THREAD

**Issue by SimonCropp** [Fody/AssemblyNeutral#6]
or should we kill of this repo?

**Comment by DamianReeves** [comment]
Been swamped at work, but I think I have a related need coming up. Lets give it a couple of months before we blow it up.
In an unrelated note, is there any reason I wouldn't be able to store s weaver using F#, considering the FSharp.Core dependency which would need to be loaded. Is ILMerge/Costura the only way?

**Comment by SimonCropp** [comment]
re merging dependencies ILMerge is better in this case

**Comment by DamianReeves** [comment]
You can kill this. I'll end up using the CoreCLR implementation of this in the future so no need to roll my own.
